name = "AbstractPlutoDingetjes"
uuid = "01723c8e-3830-11ec-16c9-d9f01e26fdcb"
authors = ["Paul Berg <paul@plutojl.org>", "Fons van der Plas <fons@plutojl.org>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia="1"